### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by mathiasbrem** [mathiasbrem/SEBC#1]

**Comment by mathiasbrem** [comment]
# My Installation Screenshots:

**1: Java Installation/Configuration _( I have installed from tarball and put in custom path, with custom profile.d and manual add at to update-alternatives_ ):**

> Oracle Java 8 SDK

![java2](https://cloud.githubusercontent.com/assets/7834310/24674265/396ab792-1951-11e7-9efc-68ee06b75548.png)

![java_1](https://cloud.githubusercontent.com/assets/7834310/24674264/39643098-1951-11e7-9391-537c5fe1ff8c.png)

**2: Configurations of sysctl -a command ( Just to check vm.swappiness):**

![sysctl](https://cloud.githubusercontent.com/assets/7834310/24674294/4f87b692-1951-11e7-824a-5bbf44e8ff20.png)

**3: Kernel parameters set on /etc/rc.local:**

![kernel](https://cloud.githubusercontent.com/assets/7834310/24674338/707c2504-1951-11e7-9975-7696e5c4a216.png)

**4: Configuration of "dns" at /etc/hosts: (getent command also) **

![hosts](https://cloud.githubusercontent.com/assets/7834310/24674356/7b9c99f0-1951-11e7-92e1-c4bd69e39cd1.png)

![getent](https://cloud.githubusercontent.com/assets/7834310/24675288/edfcc616-1954-11e7-9f35-679ade0a0edc.png)


**5: NTP ( Clock ):**

![ntp](https://cloud.githubusercontent.com/assets/7834310/24674541/2e2b684e-1952-11e7-9138-eb8c61641b3f.png)

**6: NSCD:**

![nscd](https://cloud.githubusercontent.com/assets/7834310/24675056/20de0f82-1954-11e7-9d8c-157bdfb29c8d.png)


**7: MariaDB Installation / Configuration and Replication of 2 nodes:**

**MySQL Replication ( Master -> Slave ):**

![mysql](https://cloud.githubusercontent.com/assets/7834310/24674726/ed35a5a6-1952-11e7-8ce8-788be4808147.png)

**Databases:**

![databases](https://cloud.githubusercontent.com/assets/7834310/24674727/ed379a50-1952-11e7-8db4-0e995167ff16.png)


**8: Cloudera Agent status:**

![cloudera-agent](https://cloud.githubusercontent.com/assets/7834310/24674383/8e8b676c-1951-11e7-8512-331300049594.png)


**9: Cloudera Manager after installation and configuration process:**
t
![cloudera-manager](https://cloud.githubusercontent.com/assets/7834310/24674400/9ba34294-1951-11e7-9a89-2dcaca6900b2.png)

**Comment by gwthyrpendragon** [comment]
E ae Cuzão.
